@startuml

title __LISTENERS's Class Diagram__\n

  namespace  {
    namespace om.github.saadkaleem.obd.reader.listeners {
      class com.github.saadkaleem.obd.reader.listeners.AccelerationListener {
          - lastAcceleration : float[]
          + getLastAcceleration()
          + getSensorData()
          + onAccuracyChanged()
          + onSensorChanged()
      }
    }
  }
  

  namespace  {
    namespace om.github.saadkaleem.obd.reader.listeners {
      class com.github.saadkaleem.obd.reader.listeners.GyroscopeListener {
          - lastGyroscope : float[]
          + getLastGyroscope()
          + getSensorData()
          + onAccuracyChanged()
          + onSensorChanged()
      }
    }
  }
  

  namespace  {
    namespace om.github.saadkaleem.obd.reader.listeners {
      class com.github.saadkaleem.obd.reader.listeners.OrientationListener {
          - lastDirection : String
          - lastOrientation : float
          + getLastDirection()
          + getLastOrientation()
          + getSensorData()
          + onAccuracyChanged()
          + onSensorChanged()
      }
    }
  }
  

  namespace  {
    namespace om.github.saadkaleem.obd.reader.listeners {
      interface com.github.saadkaleem.obd.reader.listeners.SensorListener {
          {abstract} + getSensorData()
      }
    }
  }
  

  com.github.saadkaleem.obd.reader.listeners.AccelerationListener .up.|> com.github.saadkaleem.obd.reader.listeners.SensorListener
  com.github.saadkaleem.obd.reader.listeners.GyroscopeListener .up.|> com.github.saadkaleem.obd.reader.listeners.SensorListener
  com.github.saadkaleem.obd.reader.listeners.OrientationListener .up.|> com.github.saadkaleem.obd.reader.listeners.SensorListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
